name: html-behave

on:
   workflow_dispatch:
    inputs:
      username:
          description: 'Username'
          required: false
jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test
        run: | 
          behave --no-capture --no-logcapture -f html -o build/all.html
          continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/build
