name: html-test-behave

on: [workflow_dispatch]

jobs:
  autotests:
    name: Run tests html report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code style
        if: always()
        run: |
          flake8

      - name: Run Test
        if: always()
        run: behave --format=html -o allure-results
        continue-on-error: true
